"""Metadata voor de 10 crash-indicatoren: teksten, eenheden, drempels en bronnen.

Per indicator:
  direction  +1 = hogere waarde is riskanter, -1 = lagere waarde is riskanter
  normal / warn / crash  niveaus waarop de drempel-score 0 / 50 / 100 is
"""

INDICATORS = {
    "yield_curve": {
        "name": "Yield Curve Inversie",
        "metric": "10-jaars minus 2-jaars Amerikaanse staatsrente",
        "unit": "%-pt", "decimals": 2, "frequency": "daily",
        "direction": -1, "normal": 1.0, "warn": 0.0, "crash": -0.75,
        "tooltip": "Verschil tussen de 10-jaars en 2-jaars rente. Onder nul = inversie, een klassiek recessiesignaal.",
        "meaning": "De yield curve vergelijkt de rente op langlopende met die op kortlopende Amerikaanse staatsobligaties. Normaal is lang geld duurder dan kort geld en is het verschil positief. Wordt het verschil negatief, dan is de curve 'geïnverteerd'.",
        "importance": "Een inversie betekent dat beleggers lagere groei en renteverlagingen verwachten. Banken lenen kort in en lang uit; bij een inversie verdwijnt hun marge en knijpen ze de kredietverlening af.",
        "history": "Voor elke Amerikaanse recessie sinds de jaren 70 was de curve geïnverteerd, onder meer in 2000, 2006-2007 en 2019. De beurs piekt vaak pas maanden later: het gevaarlijkste moment is meestal wanneer de curve na een inversie weer snel steiler wordt.",
        "source": {"name": "FRED (St. Louis Fed), reeks T10Y2Y", "url": "https://fred.stlouisfed.org/series/T10Y2Y"},
    },
    "valuation": {
        "name": "Extreme Waarderingen",
        "metric": "Shiller CAPE-ratio van de S&P 500",
        "unit": "x", "decimals": 1, "frequency": "monthly",
        "direction": 1, "normal": 20.0, "warn": 30.0, "crash": 40.0,
        "tooltip": "Koers gedeeld door de gemiddelde winst over 10 jaar, gecorrigeerd voor inflatie. Boven 30 is historisch duur.",
        "meaning": "De CAPE (cyclically adjusted price/earnings) deelt de koers van de S&P 500 door de gemiddelde reële winst over de afgelopen tien jaar. Zo worden tijdelijke winstpieken en -dalen uitgemiddeld.",
        "importance": "Hoge waarderingen voorspellen geen timing, maar wel lage rendementen over de volgende 10 jaar en een grotere val als het sentiment draait. Hoe hoger de waardering, hoe minder buffer er is voor tegenvallers.",
        "history": "De CAPE stond op 30 in 1929 en op het record van 44 in december 1999, vlak voor de dotcomcrash. Eind 2021 piekte hij rond 38, waarna de S&P 500 in 2022 ruim 25% daalde. Het langjarig gemiddelde ligt rond 17.",
        "source": {"name": "multpl.com (op basis van Robert Shiller, Yale)", "url": "https://www.multpl.com/shiller-pe/table/by-month"},
    },
    "credit_spread": {
        "name": "Kredietspreads",
        "metric": "Moody's Baa minus Aaa bedrijfsobligatierente",
        "unit": "%-pt", "decimals": 2, "frequency": "daily",
        "direction": 1, "normal": 0.8, "warn": 1.5, "crash": 2.5,
        "tooltip": "Extra rente die zwakkere bedrijven betalen boven de sterkste. Oplopende spreads wijzen op stress.",
        "meaning": "De kredietspread is het renteverschil tussen obligaties van bedrijven met een matige kredietwaardigheid (Baa) en de allerbeste (Aaa). Het is de vergoeding die beleggers vragen voor het risico op wanbetaling.",
        "importance": "Obligatiebeleggers reageren vaak eerder op verslechtering dan aandelenbeleggers. Snel oplopende spreads maken herfinanciering duurder en gaan vaak vooraf aan faillissementen en koersdalingen.",
        "history": "De spread liep op tot 3,4 %-punt eind 2008, tot circa 2 %-punt in maart 2020 en tot 1,4 %-punt in 2002. In rustige markten ligt hij tussen 0,6 en 1,0.",
        "source": {"name": "FRED, reeksen DBAA en DAAA", "url": "https://fred.stlouisfed.org/series/DBAA"},
    },
    "vix": {
        "name": "VIX-index",
        "metric": "CBOE Volatility Index",
        "unit": "", "decimals": 2, "frequency": "daily",
        "direction": 1, "normal": 15.0, "warn": 25.0, "crash": 40.0,
        "tooltip": "De 'angstindex': verwachte beweeglijkheid van de S&P 500 voor de komende 30 dagen.",
        "meaning": "De VIX wordt afgeleid uit optieprijzen op de S&P 500 en geeft de verwachte volatiliteit op jaarbasis voor de komende 30 dagen. Een VIX van 20 komt neer op een verwachte dagbeweging van ongeveer 1,25%.",
        "importance": "Een stijgende VIX laat zien dat beleggers meer betalen voor bescherming. Een zeer lage VIX wijst op zorgeloosheid, wat zelf een risico is; een sprong omhoog valt vaak samen met gedwongen verkopen.",
        "history": "De VIX sloot op 80,9 in november 2008 en 82,7 in maart 2020. Ook in augustus 2015, februari 2018 en augustus 2024 schoot hij in enkele dagen boven de 35.",
        "source": {"name": "Yahoo Finance (^VIX), reserve: FRED VIXCLS", "url": "https://finance.yahoo.com/quote/%5EVIX"},
    },
    "breadth": {
        "name": "Marktbreedte",
        "metric": "Gelijkgewogen vs. marktgewogen S&P 500 (RSP/SPY), afwijking van 200-daags gemiddelde",
        "unit": "%", "decimals": 2, "frequency": "daily",
        "direction": -1, "normal": 0.0, "warn": -3.0, "crash": -8.0,
        "tooltip": "Doet de brede markt mee met de index? Negatief = een kleine groep aandelen trekt de index.",
        "meaning": "Marktbreedte meet hoeveel aandelen meedoen aan een stijging. Hier vergelijken we de gelijkgewogen S&P 500 (RSP) met de marktgewogen index (SPY). Blijft de gelijkgewogen index achter, dan dragen steeds minder aandelen de markt.",
        "importance": "Een index die nieuwe toppen zet terwijl de meeste aandelen al dalen, is kwetsbaar: zodra de laatste koplopers omvallen is er geen steun meer.",
        "history": "In 1999-2000 steeg de index door een handvol technologieaandelen terwijl de meeste aandelen al daalden. Ook in 2007 en eind 2021 verzwakte de breedte maanden voor de top.",
        "source": {"name": "Yahoo Finance (RSP en SPY)", "url": "https://finance.yahoo.com/quote/RSP"},
    },
    "margin_debt": {
        "name": "Margin Debt",
        "metric": "Effectenkrediet bij Amerikaanse brokers, verandering op jaarbasis",
        "unit": "%", "decimals": 1, "frequency": "monthly",
        "direction": 1, "normal": 10.0, "warn": 30.0, "crash": 55.0,
        "tooltip": "Groei van beleggen met geleend geld. Snelle groei wijst op speculatie en maakt dalingen heftiger.",
        "meaning": "Margin debt is het bedrag dat beleggers bij hun broker hebben geleend om aandelen te kopen. We tonen de procentuele verandering ten opzichte van een jaar eerder.",
        "importance": "Geleend geld versterkt bewegingen. Bij dalende koersen volgen margin calls, die tot gedwongen verkopen leiden en de daling versnellen.",
        "history": "Margin debt groeide met ruim 80% op jaarbasis in maart 2000, circa 60% medio 2007 en circa 70% begin 2021. Telkens volgde binnen een jaar een forse daling.",
        "source": {"name": "FINRA Margin Statistics", "url": "https://www.finra.org/rules-guidance/key-topics/margin-accounts/margin-statistics"},
    },
    "macro": {
        "name": "Macro-data",
        "metric": "Sahm-regel: stijging werkloosheid (3-mnd gem.) boven het 12-maands dieptepunt",
        "unit": "%-pt", "decimals": 2, "frequency": "monthly",
        "direction": 1, "normal": 0.0, "warn": 0.3, "crash": 0.5,
        "tooltip": "Recessiemeter op basis van werkloosheid, aangevuld met bbp-groei en industriële productie.",
        "meaning": "De hoofdwaarde is de Sahm-regel: het driemaands gemiddelde van de Amerikaanse werkloosheid minus het laagste punt van de afgelopen 12 maanden. Daaronder tonen we bbp-groei en industriële productie als context.",
        "importance": "Beurscrashes die samenvallen met een recessie zijn dieper en duren langer. Werkloosheid die eenmaal begint te stijgen, stijgt meestal door.",
        "history": "Een waarde van 0,5 of hoger viel sinds 1970 samen met het begin van elke Amerikaanse recessie. In de zomer van 2024 tikte de regel de drempel aan zonder dat een recessie volgde.",
        "source": {"name": "FRED: UNRATE, INDPRO, A191RL1Q225SBEA", "url": "https://fred.stlouisfed.org/series/UNRATE"},
    },
    "technical": {
        "name": "Technische Breakdown",
        "metric": "S&P 500 ten opzichte van het 200-daags gemiddelde",
        "unit": "%", "decimals": 2, "frequency": "daily",
        "direction": -1, "normal": 3.0, "warn": -2.0, "crash": -12.0,
        "tooltip": "Afstand van de S&P 500 tot zijn 200-daags gemiddelde. Onder nul is de lange trend gebroken.",
        "meaning": "We berekenen het 50- en 200-daags voortschrijdend gemiddelde van de S&P 500. De hoofdwaarde is de afstand van de koers tot het 200-daags gemiddelde. Zakt het 50-daags onder het 200-daags gemiddelde, dan heet dat een 'death cross'.",
        "importance": "Veel beleggers en modellen gebruiken deze gemiddelden als trendfilter. Een breuk leidt tot verkopen door trendvolgers, wat de daling versterkt.",
        "history": "De grootste dalingen (2000-2002, 2008, 2022) speelden zich vrijwel volledig af onder het 200-daags gemiddelde. Een death cross verscheen in december 2007, maart 2020 en maart 2022.",
        "source": {"name": "Yahoo Finance (^GSPC), eigen berekening", "url": "https://finance.yahoo.com/quote/%5EGSPC"},
    },
    "earnings": {
        "name": "Earnings Deterioratie",
        "metric": "Winst per aandeel S&P 500 (12 mnd), verandering op jaarbasis",
        "unit": "%", "decimals": 1, "frequency": "monthly",
        "direction": -1, "normal": 8.0, "warn": 0.0, "crash": -15.0,
        "tooltip": "Groeit of krimpt de bedrijfswinst? Dalende winsten ondergraven de koersen.",
        "meaning": "We volgen de gerapporteerde winst per aandeel van de S&P 500 over de afgelopen 12 maanden en tonen de verandering ten opzichte van een jaar eerder.",
        "importance": "Koersen volgen op lange termijn de winsten. Krimpende winsten bij hoge waarderingen zijn een giftige combinatie: zowel de winst als de koers-winstverhouding staan dan onder druk.",
        "history": "De winsten daalden met meer dan 50% in 2001-2002 en met bijna 90% in 2008-2009. In 2015-2016 en 2022-2023 volgde op een winstdip een correctie zonder crash.",
        "source": {"name": "multpl.com (op basis van Standard & Poor's)", "url": "https://www.multpl.com/s-p-500-earnings/table/by-month"},
    },
    "liquidity": {
        "name": "Liquiditeitsstress",
        "metric": "Chicago Fed National Financial Conditions Index (NFCI)",
        "unit": "", "decimals": 2, "frequency": "weekly",
        "direction": 1, "normal": -0.5, "warn": 0.0, "crash": 1.0,
        "tooltip": "Meet krapte in geld-, krediet- en kapitaalmarkten. Boven nul is krapper dan gemiddeld.",
        "meaning": "De NFCI vat 105 maatstaven voor risico, krediet en hefboom samen in één wekelijks cijfer. Nul is het langjarig gemiddelde; positief betekent krappere financiële condities. Als context tonen we het verschil tussen de repo-rente (SOFR) en de rente op bankreserves.",
        "importance": "Crashes worden acuut wanneer financiering opdroogt: partijen moeten dan verkopen wat ze kunnen, niet wat ze willen. De TED-spread uit je oorspronkelijke opzet wordt sinds 2022 niet meer gepubliceerd (einde van LIBOR); de NFCI is de gangbare vervanger.",
        "history": "De NFCI piekte rond 3 in oktober 2008 en rond 0,3 in maart 2020. In september 2019 schoot de repo-rente in één dag naar 10% door een tekort aan reserves.",
        "source": {"name": "FRED: NFCI, SOFR, IORB", "url": "https://fred.stlouisfed.org/series/NFCI"},
    },
}

ORDER = list(INDICATORS.keys())
